### ISSUE TITLE
Absorb "awesome-openwhisk" repo. contents

### ISSUE THREAD

**Issue by mrutkows** [apache/openwhisk-website#135]
The "awesome-openwhisk" repo. (under OpenWhisk) is quote "Curated list of awesome OpenWhisk things ".  

It's link is here for convenience: https://github.com/openwhisk/awesome-openwhisk

We will want to absorb this list into the openwhisk.github.io and delete this repo. when completed.

**Comment by krook** [comment]
I think the best approach is to cherry pick content referenced from Awesome OpenWhisk and use it where it adds value here as mentioned in #48. 

That list as it stands is in the tradition of GitHub "Awesome" (and developerWorks "Recommended Reading") lists. 

If it doesn't remain within the openwhisk organization on GitHub it should move back to James Thomas' personal repo.

**Comment by daisy-ycguo** [comment]
I'd like to take this work item. I'm happy to move awesome-openwhisk to openwhisk.org.

I'm going to add the videos & presentations of a serial of OpenWhisk webinars in a Chinese program named as "IBM Open Tech Mini Academy" in this page too. Each webinar will have a presentation and a video online available. Hope the resources can be useful for all people who want to understand OpenWhisk. The serial including 6 talks:
- OpenWhisk overview
- OpenWhisk programming model introduction
- OpenWhisk tooling
- OpenWhisk usage in Micro services
- OpenWhisk usage in IoT
- Deep dive into OpenWhisk codes

Daisy
