### ISSUE TITLE
Update this repo name and description to use the openwhisk.org name rather than openwhisk.github.io

### ISSUE THREAD

**Issue by krook** [apache/openwhisk-website#153]
May need to update again in the future to include apache.org domain, but for now at least stop referring to github.io.

**Comment by krook** [comment]
Will renaming the repo cause any issues? If so, at least the description should be updated if not the repo.

**Comment by mrutkows** [comment]
I wondered if a rename would cause issues for GitHub publishing?  If not, we should rename to be conformant to our policy. i.e., openwhisk-xxx  to be something like openwhisk-website <or> openwhisk-openwhisk.org etc.

**Comment by jlengstorf** [comment]
No issues with the code itself. Just make sure to do a find-and-replace in anything that refers to this repo, and update your git remotes.

**Comment by krook** [comment]
@jlengstorf Thanks for the confirmation. Let's not invest too much time given the slight risk to do that though. 

@mrutkows At least let's change this repo description text. I don't have admin rights to do that, but it's the banner that reads "OpenWhisk website https://openwhisk.github.io" under the tabs.

**Comment by mrutkows** [comment]
We will need to change the name sooner than later and see where we self reference the repo. name as part of ASF migration.  In the meantime I will update the description. @krook
