### ISSUE TITLE
Events page needs email and/or FORM for anyone to submit blogs/candidate events

### ISSUE THREAD

**Issue by mrutkows** [apache/openwhisk-website#175]
We need to automate, for anyone in the community, a way to submit blog posts/candidate events or request approved usage of name/logo around openwhisk.  This at minimum be an email that sends a request to dev@ list (for now) and perhaps copies private@ as well (to assure attention).  

In addition, we should prescribe (require) that the request include event name (session/title name), speaker info, speaker contact info, abstract, demo info, links to existing web pages (event, source code, videos, etc.) and contact info for the submitter.

Note: that we have raised this same requirement for the "partners" page which is headed to a rename as "Supporters" as the likely top pick.

**Comment by krook** [comment]
This functionality should factor into the server-side type of Apache infrastructure we request, be it PHP, Java, Ruby, Python or whatever. Or we stay static and find a serverless form provider :)

**Comment by krook** [comment]
Would be great to reuse this work: https://github.com/IBM-Bluemix/OpenWhiskContact

**Comment by krook** [comment]
Related to #46
