### ISSUE TITLE
Add support to expand/collapse events on Events page

### ISSUE THREAD

**Issue by mrutkows** [apache/openwhisk-website#176]
The requirement came to me as: "Improve the page's layout to allow to expand/collapse events where we run multiple things."  

I believe that concern is that some events have multiple sessions and it would be nice to collapse these sessions under the event in order not to overwhelm the user/viewer (expand only as necessary, leave collapsed as default).

**Comment by krook** [comment]
This seems to already exist as demonstrated by the latest update from @nauerz-ibm in https://github.com/openwhisk/openwhisk.github.io/pull/189

Can we close @mrutkows?

**Comment by krook** [comment]
@mrutkows Can you please close this if you think the widget that's currently on the site for the InterConnect sessions suffices?
