### ISSUE TITLE
Support internationalization and Japanese language content

### ISSUE THREAD

**Issue by krook** [apache/openwhisk-website#182]

**Comment by tokida** [comment]
I am trying to transration to Japanese, but the web site is currently built in english only .
This site is built by JekyII . 
Is there  any ( favorite) approach of internationalization using JekyII.

Does anyone have an idea?

**Comment by tokida** [comment]
JekeyII-task-i18n
- This program  is not JekyII plugins.  It is able to use GitHub Pages.
- https://github.com/ruby-gettext/jekyll-task-i18n

**Comment by daisy-ycguo** [comment]
I'm also interested. I can help to translate to Chinese.

**Comment by edwardyoon** [comment]
Korean is here. ;)
