### ISSUE TITLE
website should have docs as web pages

### ISSUE THREAD

**Issue by csantanapr** [apache/openwhisk-website#183]
- need to automate the process of taking the md files from the the different repos, and generate webpages for the docs instead of linking to repos md files.

**Comment by krook** [comment]
@csantanapr this is related to #123 and #56.

**Comment by csantanapr** [comment]
Yes related, but I don't want to move the docs over this repo. 
I think we should leave the canonical docs on their respective repos

I think we should use OpenWhisk to detect doc changes in any of the repos and then submit update for the website. 

Or if we have an OpenWhisk nightly action that builds and publishes the website to apache http server
