### ISSUE TITLE
Create a new video for the home page.

### ISSUE THREAD

**Issue by jlengstorf** [apache/openwhisk-website#19]
Currently we have a placeholder from the OpenWhisk YouTube channel. 

- [ ] Record a new video to be played on the home page. (@nauerz-ibm)
- [ ] Write a script for the video (@nauerz-ibm)
- [ ] Add voice-over to the new video (@krook)
- [ ] Replace the current video on the home page (@jlengstorf)

**Comment by jthomas** [comment]
AWS Lambda has a good example of this:
https://aws.amazon.com/lambda/
