### ISSUE TITLE
Add "OpenShift" to Home page as supported deployment option

### ISSUE THREAD

**Issue by mrutkows** [apache/openwhisk-website#312]
Please validate with Red Hat (Ben/Brendan) that they are ready to have the repo. featured on the Home page first.

**Comment by dgrove-oss** [comment]
OpenShift supported by deploy-kube project.  I think this is already reflected in the website, but leaving open and assigning to me to verify

**Comment by dgrove-oss** [comment]
Confirmed that we state we support OpenShift via kube-deploy project on main web page.
