### ISSUE TITLE
Review license and copyright information

### ISSUE THREAD

**Issue by jlengstorf** [apache/openwhisk-website#37]
The original site was under the Apache license. I assume that's still valid, but wanted to add it to our launch checklist.

**Comment by nauerz-ibm** [comment]
Yes, afaik the Apache v2 is still the license of choice.
@mrutkows can confirm, for sure

**Comment by jlengstorf** [comment]
This may need revision: https://github.com/openwhisk/openwhisk.github.io/blob/master/LICENSE.txt#L190

(It says copyright IBM.)

**Comment by jlengstorf** [comment]
Other places where IBM is listed as the copyright holder or mentioned in an ownership capacity:

- https://github.com/openwhisk/openwhisk.github.io/blob/master/README.md#license
- https://github.com/openwhisk/openwhisk.github.io/blob/master/CONTRIBUTING.md#contributor-license-agreement

**Comment by krook** [comment]
@mrutkows Are these still outstanding todos?

**Comment by dgrove-oss** [comment]
obsolete.
