### ISSUE TITLE
Need to create process for adding materials to linked social media sites

### ISSUE THREAD

**Issue by krook** [apache/openwhisk-website#39]
It should be clear how content can be added to OpenWhisk social media accounts. 

That includes adding the relevant collaboration users to those accounts, or at least defining how content can be suggested to someone with access.

This would include adding videos to YouTube, adding presentations to SlideShare, articles to Medium, etc. 

Maybe a FAQ item describes the recommended process?

**Comment by jlengstorf** [comment]
The FAQ might be odd unless it's possible for _anyone_ to update social media. It's possible to create pages that aren't linked in the nav, which may be a good idea for core-team-only kind of stuff.

**Comment by jlengstorf** [comment]
We need to revisit our process for choosing channels and getting contributors to manage them. Is there Apache documentation/process in place for handling this?
