### ISSUE TITLE
Move "supporters" to a third sticky column or a new page

### ISSUE THREAD

**Issue by rabbah** [apache/openwhisk-website#420]
The supporters and icons are not prominent - they're at the bottom of the community page. We should move them up.

**Comment by vibhuti019** [comment]
Please add a screenshot
I want to work on this issue

**Comment by rabbah** [comment]
That’s great Vibhuti. Thank you. Here is a mock up courtesy of @supers1018. 

![C15FC95B-D395-4ED0-87C6-33177A02B283](https://user-images.githubusercontent.com/4959922/74297544-352cc580-4d15-11ea-801f-4371021b0e42.jpeg)

**Comment by vibhuti019** [comment]
Okay, @rabbah I am working on it.

**Comment by rabbah** [comment]
Fantastic!

**Comment by vibhuti019** [comment]
Sorry for the delay 
Please tell me how to show that in mobile view of the page?

**Comment by mrutkows** [comment]
Closed by https://github.com/apache/openwhisk-website/pull/427
