### ISSUE TITLE
Remove "Events" page as we no longer update/track them

### ISSUE THREAD

**Issue by mrutkows** [apache/openwhisk-website#444]
All the events there are outdated and maintaining old/bad links seems a waste of resource at this point...

**Comment by mrutkows** [comment]
Perhaps we should create an "archive" folder and move legacy content into it so historical info. is not lost?

**Comment by dgrove-oss** [comment]
It's in git, my inclination is always to just rm and rely on source control if we need it later.  But if you think it is important to have a web-accessible version of the old events I won't object.

**Comment by mrutkows** [comment]
@dgrove-oss just removing would be my pref. as well, just open to suggs.

**Comment by dgrove-oss** [comment]
I believe this is done.  All the old stuff is on an "Events Archive" page now.
