### ISSUE TITLE
Look at options for automating the events page.

### ISSUE THREAD

**Issue by jlengstorf** [apache/openwhisk-website#46]
Can we update the page via API?

Even better, could we use OpenWhisk to do this?

![60471003](https://cloud.githubusercontent.com/assets/163561/20906681/596ce04e-bb17-11e6-9c71-a080e107a58b.jpg)

Something to think about post-launch.

**Comment by yumeforever** [comment]
Haha Agreed!!

**Comment by jlengstorf** [comment]
So, an idea for dog-fooding this with OpenWhisk:

- If we can figure out an easy-to-manipulate-with-code format, we can effectively create an action sequence in OpenWhisk that would do something like this:

1. Event is fired by whatever API we're watching for new events.
2. Action to process that event is called, giving us a new event in a common format.
3. Action to edit the events page is called.
4. Action to submit a PR to the main repo is called. (Or, if we want to live dangerously, it can commit straight to master.)

This would likely be easier if the events were individual posts rather than a single page, but that's also a somewhat significant structural change.

The assumption here, though, is that all of these events will be loaded into a service that has an API that will send events that we can consume with OpenWhisk. Which is a big assumption. So... someone who knows how events are currently being done — @nauerz-ibm? @krook? — maybe chime in about how this has been done previously.

Or, since this is moving to an open source model, maybe we can just set up something new. It doesn't look like Lanyrd.com has an API, but maybe some other service exists that aggregates event data, and we could watch that for `#openwhisk` or something?

**Comment by krook** [comment]
I like this, but agree, it has to be in some sort of predictable format like an API. Let's start small with the Meetup API and search for keywords. 

I played around with something similar before, but never deployed it. It basically was invoked via cron and saved results to a file, which were then included as a WordPress snippet.

It looked something like this. We can use `request` in a NodeJS action.

```bash
#!/bin/bash

# Requires a Meetup.com API key: xxxxxx
# Docs: http://www.meetup.com/meetup_api/docs/2/open_events/

wget https://api.meetup.com/2/open_events?key=xxxxxx&sign=true&photo-host=public&topic=openwhisk,serverless&page=40
```

**Comment by krook** [comment]
Related to #175. FYI @csantanapr @mrutkows since we spoke about this approach.

**Comment by csantanapr** [comment]
ah it looks like @jlengstorf was thinking on META from https://github.com/openwhisk/openwhisk.github.io/issues/46#issue-193639313
