### ISSUE TITLE
Bug: broken links on download page

### ISSUE THREAD

**Issue by sebbASF** [apache/openwhisk-website#464]
The download page
https://openwhisk.apache.org/downloads.html
contains links to Cloudant package, however they are all broken.

Please fix the links or remove them.

**Comment by dgrove-oss** [comment]
We haven't released a post-incubation version of openwhisk-package-cloudant.  It looks like someone was overly eager in removing the incubating subdirectory from our dist svn.  There's been some recent discussion on whether we can revive this package or not.  I'll assign this to me to keep track of the issue.  The resolution will be either to make a 2.1.0 release of the package or to remove it from the downloads page.
