### ISSUE TITLE
slack invite is broken

### ISSUE THREAD

**Issue by rabbah** [apache/openwhisk-website#477]
Reported on the dev list, if you visit https://openwhisk.apache.org/slack.html and enter an email to request an invite, the network trace shows the request is failing
```
404 https://service.us.apiconnect.ibmcloud.com/gws/apigateway/api/3e172721d7ba44ac0cb5633eae516fb1284fd9a45633e4172dbe7a780b6572c6/api/slackinvite?email=someid@gmail.com
```

@csantanapr i think you set this up?

**Comment by csantanapr** [comment]
Yeah but I don't have access to that action anymore. 
I'm ok if you want to run the action in nimbella cloud

**Comment by csantanapr** [comment]
I think this is the code https://github.com/csantanapr/openwhisk-slackinvite

**Comment by rabbah** [comment]
Thanks for the pointer, I will look at switching it over.

**Comment by csantanapr** [comment]
Have one of your new engineers contribute the change 😉

**Comment by rabbah** [comment]
ha!

but i do have a PR that you're going to ❤️ 🤯
