### ISSUE TITLE
Add a section to inspire people (blog and/or tutorials)

### ISSUE THREAD

**Issue by jlengstorf** [apache/openwhisk-website#53]
What would this take?

Putting this in the icebox to revisit post-launch.

**Comment by krook** [comment]
This interactive NPM CLI provides a starting point: https://github.com/openwhisk/openwhisk-tutorial

**Comment by krook** [comment]
@nauerz-ibm Was also going to add his ServerlessConf UK workshop materials.

**Comment by jthomas** [comment]
We also maintain this list:
https://github.com/openwhisk/awesome-openwhisk

**Comment by jthomas** [comment]
I've always liked the regular "This Week/Month/Quarter in <technology>" posts or newsletters. 
It's a good way to help people understand what cool stuff is being built. 
This could be done as a blog post.

**Comment by jlengstorf** [comment]
There's an epic discussing how to incorporate content like this (#123). Let's focus discussion there to keep it in one place for now.
