### ISSUE TITLE
Lower the barrier to getting started as quickly as possible as a developer

### ISSUE THREAD

**Issue by krook** [apache/openwhisk-website#56]
Ideas:
- Should have an interactive online wsk interpreter? Similar to the [Swift Sandbox](https://swiftlang.ng.bluemix.net/#/repl)?
- Neutral page linking to online OpenWhisk providers, such as Bluemix
- Orchestrate/deploy a cluster to a cloud provider
- Links to the [Ansible playbooks](https://github.com/openwhisk/openwhisk/tree/master/ansible) on OpenStack (and someday [Kubernetes](https://github.com/openwhisk/openwhisk/issues/1402)) installs

**Comment by jthomas** [comment]
I know @mrutkows had someone working on a clone of the interactive Docker tool for OpenWhisk.
https://github.com/openwhisk/openwhisk-tutorial

It was running at https://learnwhisk.mybluemix.net/#0 but it wasn't clear whether this was a permanent URL.

It's a brilliant tool.

**Comment by jthomas** [comment]
I think having a "Getting Started" page rather than linking straight into the open-source docs would make an easy onboarding experience. 

It could have steps for deploying it yourself or linking to the current providers.

**Comment by jlengstorf** [comment]
Most users will be interested in technical features — we need to make sure that's accessible and prominent.
