### ISSUE TITLE
Add "Tutorials & Examples" section.

### ISSUE THREAD

**Issue by jthomas** [apache/openwhisk-website#98]
Once I understand what OpenWhisk is, I want to learn how to use it. 
Going past the usual "Hello World" samples, it would be great to have a few tutorials for particular use-cases to highlight key features of the platform. 

People have already created some awesome demos with OpenWhisk, maybe we could merge that content into the site for a quick win?

**Comment by jlengstorf** [comment]
Same as #99, would you be able to pull together a list of the existing demos? That'll help us have a discussion about how to incorporate them into the site.

**Comment by jthomas** [comment]
Here's a list of the most interesting demos... 

https://github.com/IBM-Bluemix/skylink
https://github.com/IBM-Swift/BluePic
https://github.com/krook/openfridge
https://github.com/krook/openchecks
https://github.com/krook/owplan
https://github.com/jthomas/microservices_without_servers/tree/master/code/weather_bot

**Comment by jlengstorf** [comment]
Discussion about this has been opened on #123. Let's keep comments there for simplicity.
