### ISSUE TITLE
Add existing material to "Events" page.

### ISSUE THREAD

**Issue by jthomas** [apache/openwhisk-website#99]
It would be good to have the Events page list upcoming sessions and material from previous sessions. 

We have lots of videos, slides and resources available from talks people have done in 2016.
https://github.com/openwhisk/awesome-openwhisk#media

Could pick the best examples and add them to the site? Use embedding widgets from Youtube to show the videos inline.

**Comment by krook** [comment]
Related to #48

**Comment by jlengstorf** [comment]
I think a great first step would be to compile links to these tutorials. Do you have them, @jthomas?

I'll assign this to you for now, but feel free to reassign if someone else is better-suited to compile the links.

**Comment by jthomas** [comment]
Looking over the list of videos, here's a nice selection:

Good overview of the project from @krook, short and longer verions....
https://www.youtube.com/watch?v=sYRiTZ47Cao
https://www.youtube.com/watch?v=C3PPmlUkarY

This is the best video of my serverless talk: https://www.youtube.com/watch?v=t4-a8H_zT54
It's a longer talk including the history of serverless and a demo session.

The OpenWhisk team have done the general OW intro here:
https://www.youtube.com/watch?v=rVGFll1sRY4

I also like this "OW under the hood talk" 
https://www.youtube.com/watch?v=S-fY1exdbao

**Comment by jlengstorf** [comment]
Discussion about this has been opened on #123. Let's keep comments there for simplicity.
